import type { Metadata } from "next";
import { Italianno, Eczar } from "next/font/google";
import "./globals.css";

const italianno = Italianno({
  weight: "400",
  variable: "--font-italianno",
  subsets: ["latin"],
});

const eczar = Eczar({
  subsets: ["latin"],
  variable: "--font-eczar",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italianno.variable} ${eczar.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
