import type { Metadata } from "next";
import { Italianno, Eczar, Inter } from "next/font/google";
import "./globals.css";

const italianno = Italianno({
  weight: "400",
  variable: "--font-italianno",
  subsets: ["latin"],
});

const eczar = Eczar({
  subsets: ["latin"],
  variable: "--font-eczar",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${italianno.variable} ${eczar.variable} ${inter.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
